version: '3'

services:
  gofastcom:
    container_name: "gofastcom"
    build:
      context: "."
      dockerfile: "Dockerfile"
    volumes: # https://flaviocopes.com/docker-access-files-outside-container/
      - ./:/gofastcom/
